major update of alta website
altaexec/alta-website pull request #2
Opened 2019-05-16 22:59 UTC by daixiangau

Change the UI and delete some out-of-date contents.

2019-05-16 23:45 UTC, daixiangau commented
major update of alta website
update brochure

2019-05-19 07:34 UTC, admackin requested changes
Looks great! Just a couple of minor things

2019-05-19 07:34 UTC, admackin commented on index.html
> +            (ALTA 2019) was held from the 4th-6th of December at the
```suggestion
            (ALTA 2019) will be held from the 4th-6th of December at the
```

2019-05-19 07:34 UTC, admackin commented on _layouts/home.html
> +         <a style="float: left; height: 50px; padding: 15px 25px; font-size: 18px; line-height: 20px; text-transform: uppercase; color: #eee" href="index.html">Home</a>
as above

2019-05-19 08:47 UTC, daixiangau commented
updated

2019-05-21 04:47 UTC, daixiangau commented
I fix the typo of home page; put these styles in the css file.

2019-06-02 01:36 UTC, merged